### ISSUE TITLE
Artifacts？

### ISSUE THREAD

**Issue by VarLad** [gstavrinos/ROS.jl#1]
Any plans on including ROS as an artifact？

**Comment by gstavrinos** [comment]
ROS.jl has been registered as a package (https://github.com/JuliaRegistries/General/pull/26418). It will require some time to get accepted since there are also conflicts with the naming guidelines. Feel free to re-open the issue or open a new one if you have any more questions.

**Comment by VarLad** [comment]
Since installing ROS on any OS which is not Ubuntu or Debian based Linux is a pain, I think ROS artifact would be an awesome idea！
Plus BinaryBuilder is a great package and the devs are really helping too！

**Comment by gstavrinos** [comment]
Thanks for the insight, @clad26! I will look into it!

**Comment by VarLad** [comment]
I mean, if people can use ROS using Julia, by typing `]add ROS`, without having ROS pre-installed, that alone would attract a lot of users to ROS.jl and Robotics in Julia.

**Comment by gstavrinos** [comment]
Sure, that's I will look into it and see how much of a viable solution that would be. Thanks again!
