### ISSUE TITLE
Differences between ROS.jl and RobotOS.jl

### ISSUE THREAD

**Issue by ferrolho** [gstavrinos/ROS.jl#4]
Hi! This repository looks interesting. How does ROS.jl compare with [RobotOS.jl](https://github.com/jdlangs/RobotOS.jl)?

**Comment by gstavrinos** [comment]
Hey, thanks for the interest. The main difference is that RobotOS.jl is a wrapper of the Python client and ROS.jl is a wrapper of the C++ client. 

Which one you would choose, really depends on your needs. If you seek full stability and reliability, RobotOS.jl is the way to go. It has been around for a while now, and ROS.jl has not been tested enough (it's not in a `stable` release yet). If you need the C++ speed and you are willing to encounter bugs/shortages ROS.jl has something to offer.

I hope I helped you.

**Comment by ferrolho** [comment]
Yes. Thank you for your prompt reply!
