### ISSUE TITLE
Is newer julia versions planned

### ISSUE THREAD

**Issue by ga72kud** [gstavrinos/ROS.jl#8]
Are there newer Julia versions planned? In the documentation, it says:     Julia 1.3 (due to current Cxx limitations)

**Comment by gstavrinos** [comment]
Hey, thanks for your interest in the package. In order for future versions of ROS.jl to be useful and stalbe, I will have to port it to CxxWrap. This is not a straight-forward task. I would definitely love to do it at some point, but I don't have the time availability currently.

I am closing this issue, but feel free to re-open it! :)

**Comment by chelseas** [comment]
Would you be willing to start a list of tasks that need to be performed in order to update ROS.jl to CxxWrap.jl and maybe people can contribute one task at a time?

**Comment by gstavrinos** [comment]
Hello Chelsea,

Sorry for the late reply. I lost the e-mail, and just found out about your issue, while scrolling to find some other stuff.

As you might have guessed already, I am not currently working on this project anymore. With ROS1 going EOL in just a few months, I think it's a lost cause to try and update this repo. I have some work done (in a private repo) on a ROS2 implementation, but it's a really old version and ROS2 has moved on a lot from that point. I think that a completely new implementation would be the best starting point. If you are willing to look into it, maybe we could discuss about a list of required first steps. 

George
